apiVersion: v1

kind: Service
metadata:
  name: backend-service
  spec:
    selector:
      app: kub-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    type: LoadBalancer